# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qcomp-ESR/ESRWorking/ESRWorkingProgram/CW_ESR/GUI_v3.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1089, 678)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 911, 291))
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 310, 561, 311))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 251, 277))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.startFreqGHzLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.startFreqGHzLabel.setObjectName("startFreqGHzLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.startFreqGHzLabel)
        self.startFreqLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.startFreqLineEdit.setObjectName("startFreqLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.startFreqLineEdit)
        self.stopFreqGHzLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.stopFreqGHzLabel.setObjectName("stopFreqGHzLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.stopFreqGHzLabel)
        self.stopFreqLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.stopFreqLineEdit.setObjectName("stopFreqLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stopFreqLineEdit)
        self.stepFreqGHzLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.stepFreqGHzLabel.setObjectName("stepFreqGHzLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.stepFreqGHzLabel)
        self.stepsLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.stepsLineEdit.setObjectName("stepsLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.stepsLineEdit)
        self.numOfAvgsLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.numOfAvgsLabel.setObjectName("numOfAvgsLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.numOfAvgsLabel)
        self.numOfAvgsLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.numOfAvgsLineEdit.setObjectName("numOfAvgsLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.numOfAvgsLineEdit)
        self.powerSynLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.powerSynLabel.setObjectName("powerSynLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.powerSynLabel)
        self.powerSynSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.powerSynSpinBox.setMaximum(3)
        self.powerSynSpinBox.setObjectName("powerSynSpinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.powerSynSpinBox)
        self.powerAmpLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.powerAmpLabel.setObjectName("powerAmpLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.powerAmpLabel)
        self.powerAmpSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.powerAmpSpinBox.setMaximum(63)
        self.powerAmpSpinBox.setSingleStep(0)
        self.powerAmpSpinBox.setObjectName("powerAmpSpinBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.powerAmpSpinBox)
        self.dwellTimeMsLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.dwellTimeMsLabel.setObjectName("dwellTimeMsLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.dwellTimeMsLabel)
        self.dwellTimeLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.dwellTimeLineEdit.setObjectName("dwellTimeLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dwellTimeLineEdit)
        self.powerOutputLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.powerOutputLineEdit.setEnabled(True)
        self.powerOutputLineEdit.setObjectName("powerOutputLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.powerOutputLineEdit)
        self.powerEstiDBLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.powerEstiDBLabel.setObjectName("powerEstiDBLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.powerEstiDBLabel)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(270, 30, 291, 277))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.alternatorPowerLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.alternatorPowerLabel.setObjectName("alternatorPowerLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.alternatorPowerLabel)
        self.attPowerLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.attPowerLineEdit.setObjectName("attPowerLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.attPowerLineEdit)
        self.laserWavelengthLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.laserWavelengthLabel.setObjectName("laserWavelengthLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.laserWavelengthLabel)
        self.laserWavelengthLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.laserWavelengthLineEdit.setObjectName("laserWavelengthLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.laserWavelengthLineEdit)
        self.laserPowerLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.laserPowerLabel.setObjectName("laserPowerLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.laserPowerLabel)
        self.laserPowerLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.laserPowerLineEdit.setObjectName("laserPowerLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.laserPowerLineEdit)
        self.dwellTimeMsLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.dwellTimeMsLabel_2.setObjectName("dwellTimeMsLabel_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.dwellTimeMsLabel_2)
        self.freqValueAtDipLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.freqValueAtDipLineEdit.setEnabled(False)
        self.freqValueAtDipLineEdit.setObjectName("freqValueAtDipLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.freqValueAtDipLineEdit)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(580, 310, 221, 311))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButtonStart = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonStart.setGeometry(QtCore.QRect(20, 30, 93, 28))
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.pushButtonStop = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonStop.setEnabled(False)
        self.pushButtonStop.setGeometry(QtCore.QRect(120, 30, 93, 28))
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 70, 201, 221))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 60, 53, 16))
        self.label.setObjectName("label")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(810, 310, 271, 311))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButtonSave = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonSave.setEnabled(False)
        self.pushButtonSave.setGeometry(QtCore.QRect(20, 30, 93, 28))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonDiscard = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonDiscard.setEnabled(False)
        self.pushButtonDiscard.setGeometry(QtCore.QRect(160, 30, 93, 28))
        self.pushButtonDiscard.setObjectName("pushButtonDiscard")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(20, 130, 231, 22))
        self.comboBox.setObjectName("comboBox")
        self.pushButtonPrev = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonPrev.setEnabled(False)
        self.pushButtonPrev.setGeometry(QtCore.QRect(20, 230, 93, 28))
        self.pushButtonPrev.setObjectName("pushButtonPrev")
        self.pushButtonNext = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonNext.setEnabled(False)
        self.pushButtonNext.setGeometry(QtCore.QRect(160, 230, 93, 28))
        self.pushButtonNext.setObjectName("pushButtonNext")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1089, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CW ESR"))
        self.groupBox.setTitle(_translate("MainWindow", "Parameters"))
        self.startFreqGHzLabel.setText(_translate("MainWindow", "Start Freq (GHz)"))
        self.stopFreqGHzLabel.setText(_translate("MainWindow", "Stop Freq (GHz)"))
        self.stepFreqGHzLabel.setText(_translate("MainWindow", "Num of Steps"))
        self.numOfAvgsLabel.setText(_translate("MainWindow", "Num of Avgs"))
        self.powerSynLabel.setText(_translate("MainWindow", "Power Syn"))
        self.powerAmpLabel.setText(_translate("MainWindow", "Power Amp"))
        self.dwellTimeMsLabel.setText(_translate("MainWindow", "Dwell Time (ms)"))
        self.powerEstiDBLabel.setText(_translate("MainWindow", "Power Output (dB)"))
        self.alternatorPowerLabel.setText(_translate("MainWindow", "Attenuator Power (dB)"))
        self.laserWavelengthLabel.setText(_translate("MainWindow", "Laser Wavelength (nm)"))
        self.laserWavelengthLineEdit.setPlaceholderText(_translate("MainWindow", "532"))
        self.laserPowerLabel.setText(_translate("MainWindow", "Laser Power (dB)"))
        self.dwellTimeMsLabel_2.setText(_translate("MainWindow", "Freqency Value at Dip (GHz)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Control"))
        self.pushButtonStart.setText(_translate("MainWindow", "Start"))
        self.pushButtonStop.setText(_translate("MainWindow", "Stop"))
        self.label.setText(_translate("MainWindow", "Log"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Data"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save"))
        self.pushButtonDiscard.setText(_translate("MainWindow", "Discard"))
        self.pushButtonPrev.setText(_translate("MainWindow", "Previous"))
        self.pushButtonNext.setText(_translate("MainWindow", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
